### ISSUE TITLE
filenotfounderror: no such file or directory:'data/visual_genome/vocab.json'

### ISSUE THREAD

**Issue by googlelee** [yikang-li/PasteGAN#3]
I cannot find the voca.json in the public website of genome and coco , is this file produced in the pre-processing?

Could you kindly provide it for me?

**Comment by superkoma** [comment]
Thanks for your interest. vocab.json is the product of data pre-processing, and we are cleaning this part. We will upload these files after recent works.

**Comment by buaaswf** [comment]
Hi@superkoma, have you uploaded the vocab.json, without it we cannot test this code.
Thanks,

**Comment by alibabadoufu** [comment]
Hi @superkoma, can you upload this file?

**Comment by superkoma** [comment]
Hi,

The data is uploaded and the link can be founded in README.
