### ISSUE TITLE
Double perceptual loss

### ISSUE THREAD

**Issue by hytseng0509** [yikang-li/PasteGAN#4]
Hi,

Thanks for sharing the code. May I ask what's the purpose of the double perceptual loss [here](https://github.com/yikang-li/PasteGAN/blob/e1dd27d9ac76d1879c117b614af49e65fe429f21/train.py#L309)?

It seems not introduced in your paper. Thanks!

**Comment by superkoma** [comment]
Hi,
double perceptual loss is introduced in last line of Page 6 of our paper.
