### ISSUE TITLE
train.h5

### ISSUE THREAD

**Issue by alibabadoufu** [yikang-li/PasteGAN#5]
OSError: Unable to open file (unable to open file: name = 'data/visual_genome/train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

There are some missing files in your folder, which are vocab.json and train.h5. May I know when would you able to upload them?

**Comment by alibabadoufu** [comment]
I managed to preprocess these files [test.h5,train.h5,val.h5,vg_splits.json,vocab.json] with reference from LostGan repo and SG2IM repo. However, I am still missing objects.csv file.

**Comment by gonghuiyun** [comment]
Hello, I encountered the same problem, is it solved? How to get csv file? Thank you!

**Comment by superkoma** [comment]
Hi ALL, the data is uploaded and the link can be found in README.
